#+Title: "Sobre la materia"
#+STARTUP: showall expand
#+options: toc:nil

#+begin_src yaml :exports results :results value html
---
layout: default
title: Sobre el curso
weight: 10
---
#+end_src
#+results:

** Carreras
- PGU en Ciencias Básicas con orientación en Biología, Física, Matemática, Geología y Química.
- Licenciatura en Ciencias Básicas con orientación en Biología, Física, Matemática, Geología y
  Química.
- La materia también es válida como curso de posgrado.

** Cursado no presencial
- Se podrá cursar de manera /no presencial/, lo que implica la posibilidad de no asistir a clases teóricas, pero aún así acceder a los créditos de la materia.
- Será obligatorio para regularizar:
  - Inscribirse en SIU Guaraní.
  - Rendir los exámenes parciales.
  - Entregar el informe escrito final.
- En esta modalidad, se dispondrá de acceso online a las clases dictadas, y a consulta online con los profesores y el resto de los alumnos de la materia. Adicionalmente, se podrá acceder a bibliografía adicional y se tendrá la posibilidad de consulta /in situ/ en días previamente acordados con la cátedra.

** Programas

- [Programa para graduación]({{ site.url }}/assets/Programa - Análisis de Datos Científicos en R.pdf)
- [Programa para posgraduación]({{ site.url }}/assets/Programa - Análisis de Datos Científicos en R - Posgrado.pdf)

** Objetivos
1) Dominar los conceptos básicos del lenguaje de programación R.
2) Desarrollar e implementar programas y scripts en el lenguaje R con foco en el análisis de datos empíricos.
3) Comprender las ventajas y desventajas del lenguaje R y como se complementa con otros lenguajes de programación y técnicas de análisis de datos.
4) Conocer las fuentes de información necesarias para acceder de manera independiente al conocimiento requerido para resolver problemas científicos específicos.
5) Implementar los conocimientos de programación conseguidos para desarrollar modelos científicos
   para resolver problemas simples en diferentes áreas del conocimiento.

** Créditos del sitio web
Esta web está construida con [[https://jekyllrb.com/][Jekyll]] + [[https://github.com/hakimel/reveal.js][Reveal.js]] (este último de [[https://hakim.se/][Hakim El Hattab]]), y está fuertemente basado en el
[[https://jennybc.github.io/purrr-tutorial/][Tutorial de purrr de Jenny Brian]]. El código fuente de esta página está en disponible en [[https://github.com/r-lectures/r-lectures.github.io][Github]], que hace a su vez
de host del sitio a través de su servicio [[https://pages.github.com/][Github Pages]]. 
