#+Title: "Sobre el curso"
#+STARTUP: showall expand
#+options: toc:nil

#+begin_src yaml :exports results :results value html
---
layout: default
title: Sobre el curso
weight: 10
---
#+end_src
#+results:

** Carrera/s:
- PGU en Ciencias Básicas con orientación en Biología, Física, Matemática, Geología y Química
- Licenciatura en Ciencias Básicas con orientación en Biología, Física, Matemática, Geología y Química
** [Programa]({{ site.url }}/assets/programa2017.pdf)
** Objetivos
1) Dominar los conceptos básicos del lenguaje de programación R.
2) Desarrollar e implementar programas y scripts en el lenguaje R con foco en el análisis de datos empíricos.
3) Comprender las ventajas y desventajas del lenguaje R y como se complementa con otros lenguajes de programación y técnicas de análisis de datos.
4) Conocer las fuentes de información necesarias para acceder de manera independiente al conocimiento requerido para resolver problemas científicos específicos.
5) Implementar los conocimientos de programación conseguidos para desarrollar modelos científicos para resolver problemas simples en diferentes áreas del conocimiento.
