#+title: Programación y análisis de datos en R con aplicaciones científicas - 2017
#+STARTUP: showall expand
#+options: toc:nil

#+begin_src yaml :exports results :results value html 
--- 
layout: default 
title: index 
--- 
#+end_src 
#+results:
* Programación y análisis de datos en R con aplicaciones científicas 

Este curso tiene como objetivo enseñar el lenguaje de programación R como una herramienta útil
para la investigación científica. Nos proponemos explorar el lenguaje y su ecosistema de paquetes,
funciones y demás elementos relacionados, desde un punto de vista práctico. No haremos hincapié en
aprender a programar en si (aunque necesariamente cubriremos lo básico), si no más bien pondemos el
foco como usar el lenguaje de manera eficaz para los objetivos científicos de cada uno. 

El lenguaje R está fuertemente relacionado con dos áreas de las cuales se ha nutrido desde su
concepción: la estadística y el análisis de datos. Por ello, a lo largo del curso vamos a usar
elementos de ambas áreas como soporte para explorar en detalle las distintas utilidades de este
flexible lenguaje de programación.

** Horarios
Martes y Miércoles, de 9:00 a 12:00 en la sala de computación
** Prof. Luis G. Moyano 
- Inv. Adjunto CONICET y Prof. Adjunto FCEN
- Física Estadística y sistemas complejos
- mail: _lgmoyano@gmail.com_ / twitter: @luisgmoyano
- Me encuentran principalmente a la mañana en la oficina 904 (al final del edificio, por la escalera norte)
** Herramientas
- [[https://www.rstudio.com/][RStudio]] - para trabajar con R
  - Alternativamente, pueden usar R en una terminal (por ejemplo, bash u otra) + el editor de texto que quieran ([[https://www.gnu.org/software/emacs/][emacs]], o si no hay otra, [[http://www.vim.org/][vim]] ;)
- [[https://slack.com/][Slack]] - para mantenernos en contacto entre todos
- [[https://github.com/][Github]] - para compartir código
