#+title: Análisis de datos científicos en R - 2019
#+STARTUP: showall expand
#+options: toc:nil

#+begin_src yaml :exports results :results value html 
--- 
layout: default 
title: index 
--- 
#+end_src 
#+results:
* Análisis de Datos Científicos en R

Este curso tiene como objetivo transmitir los principales conceptos para el análisis de datos con el
lenguaje R y entrenar en su utilización, ya que es una herramienta muy eficiente y versátil para la
investigación científica.  Nos proponemos explorar, desde un punto de vista eminentemente práctico,
el lenguaje y su ecosistema de paquetes, funciones y demás elementos relacionados.  No haremos
demasiado hincapié en aprender a programar en sí (aunque necesariamente cubriremos lo básico), si no
más bien pondremos el foco en como usar el lenguaje de manera eficaz, siempre con los objetivos
científicos en el horizonte.

El lenguaje R está fuertemente relacionado con dos áreas de las cuales se ha nutrido desde su
origen: la estadística y el análisis de datos empíricos. Por ello, a lo largo del curso, vamos a usar
elementos de ambas áreas como soporte para explorar en detalle las distintas utilidades de este
flexible lenguaje de programación.

** Horarios y Fechas
- Lunes de 15:00 a 18:00 y Miércoles de 16:00 a 19:00.
- Fecha de inicio: 18 de Marzo de 2018.
- Duración: 36 hs presenciales - 80 hs para carreras de grado, 120 hs para carreras de posgrado.
- La materia de dicta en la sala de informática.
- Se recomienda traer laptop, si se tiene esa posibilidad.

** Herramientas
- [[https://www.rstudio.com/][RStudio]] - aunque opcional, se lo recomienda para trabajar con R.
  - Alternativamente, pueden usar R en una terminal (por ejemplo, bash u otra) más el editor de texto
    que quieran (por ejemplo, [[https://www.gnu.org/software/emacs/][emacs]] o, si no hay otra, [[http://www.vim.org/][vim]] ;)
- [[https://slack.com/][Slack]] - para coordinarnos entre los miembros del curso.
- [[https://github.com/][Github]] - recomendable para compartir código.

*** Prof. Luis G. Moyano 
- Inv. Adjunto CONICET y Prof. Adjunto FCEN, UNCU.
- Física Estadística y Sistemas Complejos.
- Mi oficina es la 904 (al final del edificio, por la escalera norte).
- _lgmoyano@gmail.com_ / twitter: [[https://twitter.com/luisgmoyano][@luisgmoyano]]
