#+title: Programación y análisis de datos en R con aplicaciones científicas - 2017
#+STARTUP: showall expand
#+options: toc:nil

#+begin_src yaml :exports results :results value html 
--- 
layout: default 
title: index 
--- 
#+end_src 
#+results:
* Programación y análisis de datos en R con aplicaciones científicas 

Este curso tiene como objetivo transmitir los principales conceptos del lenguaje de programación R y
entrenar en su utilización ya que es una útil herramienta para la investigación científica. Nos
proponemos explorar, desde un punto de vista eminentemente práctico, el lenguaje y su ecosistema de
paquetes, funciones y demás elementos relacionados. No haremos hincapié en aprender a programar en
sí (aunque necesariamente cubriremos lo básico), si no más bien pondremos el foco en como usar el
lenguaje de manera eficaz, siempre con los objetivos científicos en el horizonte.

El lenguaje R está fuertemente relacionado con dos áreas de las cuales se ha nutrido desde su
origen: la estadística y el análisis de datos empíricos. Por ello, a lo largo del curso, vamos a usar
elementos de ambas áreas como soporte para explorar en detalle las distintas utilidades de este
flexible lenguaje de programación.

** Fechas y Horarios
- Martes y Miércoles, de 9:00 a 12:00
- Fecha de inicio: 18 de Abril
- Duración: 48 hs (8 semanas) para carreras de grado, 60 hs (10 semanas) para carreras de posgrado
- La materia de dicta en la sala de computación

** Herramientas
- [[https://www.rstudio.com/][RStudio]] - para trabajar con R
  - Alternativamente, pueden usar R en una terminal (por ejemplo, bash u otra) más el editor de texto
    que quieran (por ejemplo, [[https://www.gnu.org/software/emacs/][emacs]] o, si no hay otra, [[http://www.vim.org/][vim]] ;)
- [[https://slack.com/][Slack]] - para mantenernos en contacto entre todos
- [[https://github.com/][Github]] - para compartir código

*** Prof. Luis G. Moyano 
- Inv. Adjunto CONICET y Prof. Adjunto FCEN
- Física Estadística y sistemas complejos
- Me encuentran principalmente a la mañana en la oficina 904 (al final del edificio, por la escalera norte)
- _lgmoyano@gmail.com_ / twitter: [[https://twitter.com/luisgmoyano][@luisgmoyano]]
